Attempt to stabilize tests (#45)
1. Turn off Gradle parallel run of test from different modules:
Two tests using Solana Test Validator were started currently, the 2nd
test would reuse running validator, then 1st test would finish and close
the validator leaving the 2nd test that was running without an available
validator.

2. This exposed some Corda OS test imports messing with ENT complied
code:
```
java.lang.NoSuchMethodError: 'void net.corda.nodeapi.internal.persistence.CordaPersistence.start(javax.sql.DataSource, java.lang.String)'
	at net.corda.node.migration.CordaMigration$initialiseNodeServices$1.invoke(CordaMigration.kt:119)
```

3. This exposed that on Jenkins somehow the code is run against latest
Corda Enterprise snapshot while it is complied against older one, for
example a class was introduced recently in 4.14:
```
Caused by: java.lang.NoClassDefFoundError: net/corda/nodeapi/exceptions/ReadOnlyNodeException 
```
Fix - versions were updated to the latest built snapshots.